---
- name: Install and configure Nginx on Ubuntu
  hosts: test
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install soft
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - php8.1-fpm
        - certbot
        - python3-certbot-nginx

    - name: Start soft and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php8.1-fpm

    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: 0644
        backup: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
